const imagesData = {
  selectedWork: {
    id: 'selected-work',
    title: 'Selected Work',
    slug: 'photography-selected-work',
    heroText: 'A focused edit of the strongest images across portraiture, atmosphere, still life, and visual experimentation.',
    webDescription: 'This shortlist is built as a first portfolio edit for a professional website. The selection favors range, clarity, and visual confidence, bringing together images that feel most capable of attracting clients, creative collaborators, and job opportunities. It is less about showing everything and more about presenting a sharp point of view.',
    metaDescription: 'A curated portfolio shortlist featuring standout portrait, conceptual, still life, and atmospheric photography.',
    sourceFolder: '00_Portfolio_Shortlist'
  },
  categories: [
    {
      id: 'portrait-narratives',
      title: 'Portrait Narratives',
      slug: 'photography-portrait-narratives',
      heroText: 'Human-centered portraits built around presence, character, and quiet storytelling.',
      webDescription: 'These portraits focus on people, mood, and connection. The images feel cleaner and more grounded than the conceptual work, but still carry a clear sense of style through light, color, pose, and framing. This section is suited to editorial portraiture, personal branding, lifestyle stories, and artist-focused work.',
      metaDescription: 'Editorial and story-driven portrait photography centered on mood, identity, and presence.',
      sourceFolder: '02_Portrait_Narratives',
      isPrimary: true
    },
    {
      id: 'posters-key-art',
      title: 'Posters And Key Art',
      slug: 'photography-posters-key-art',
      heroText: 'Graphic image-making for posters, covers, campaign visuals, and visual identity work.',
      webDescription: 'This section combines photography with design, compositing, and treatment-driven image building. The result is work that feels closer to cover art, poster design, and promotional visuals than to straight photography alone. It is especially relevant for music artists, personal brands, event campaigns, and image-based storytelling that needs a stronger graphic edge.',
      metaDescription: 'Poster design, cover art, and graphic photo treatments for campaigns, music visuals, and branding.',
      sourceFolder: '06_Posters_And_Key_Art',
      isPrimary: true
    },
    {
      id: 'product-commercial',
      title: 'Product And Commercial',
      slug: 'photography-product-commercial',
      heroText: 'Product-focused imagery designed around detail, texture, shape, and visual appeal.',
      webDescription: 'This gallery is the most directly commercial section of the archive. It highlights items, materials, and product details through clean framing, contrast, and emphasis on surface quality. The work fits brands, catalog-style use, campaign assets, and social media visuals that need a polished and saleable look.',
      metaDescription: 'Commercial product photography focused on detail, texture, styling, and brand-ready presentation.',
      sourceFolder: '04_Product_And_Commercial',
      isPrimary: true
    },
    {
      id: 'editorial-still-life',
      title: 'Editorial Still Life',
      slug: 'photography-editorial-still-life',
      heroText: 'Arranged objects, quiet light, and detail-driven compositions with an editorial feel.',
      webDescription: 'This section brings together still life photographs built from books, coffee, props, and everyday textures. The images rely on composition, atmosphere, and restraint to create a slower and more intentional visual rhythm. They can support editorial storytelling, publishing projects, lifestyle brands, and more intimate web layouts.',
      metaDescription: 'Editorial still life photography featuring objects, texture, atmosphere, and carefully arranged compositions.',
      sourceFolder: '03_Editorial_Still_Life',
      isPrimary: true
    },
    {
      id: 'conceptual-portraits',
      title: 'Conceptual Portraits',
      slug: 'photography-conceptual-portraits',
      heroText: 'Portraiture shaped by motion, distortion, layering, and visual experimentation.',
      webDescription: 'This gallery explores portrait photography as mood, tension, and transformation rather than simple representation. Blur, surreal framing, graphic interventions, and altered color create images that feel expressive and cinematic. The work is aimed at viewers looking for a stronger visual signature and a more authored creative voice.',
      metaDescription: 'Experimental portrait photography with motion blur, surreal edits, and cinematic atmosphere.',
      sourceFolder: '01_Conceptual_Portraits',
      isPrimary: true
    },
    {
      id: 'night-neon',
      title: 'Night And Neon',
      slug: 'photography-night-neon',
      heroText: 'Urban night photography driven by glow, shadows, and after-dark atmosphere.',
      webDescription: 'These images are built from street light, neon spill, reflections, and the slower tension of night. The work moves between documentary mood and cinematic suggestion, using darkness as part of the composition rather than a limitation. It is a strong section for atmosphere, music-related visuals, and story-led portfolio pacing.',
      metaDescription: 'Atmospheric night photography with neon light, urban mood, reflections, and cinematic darkness.',
      sourceFolder: '05_Night_And_Neon',
      isPrimary: false
    },
    {
      id: 'architecture-place',
      title: 'Architecture And Place',
      slug: 'photography-architecture-place',
      heroText: 'Buildings, streets, and spatial fragments observed through atmosphere, geometry, and location.',
      webDescription: 'This section focuses on the character of place. Some images emphasize structure and geometry, while others rely on mood, scale, and urban texture. Together they show an eye for environments and visual context, making the work suitable for editorial, travel, cultural, and location-based storytelling.',
      metaDescription: 'Architecture and place photography featuring urban atmosphere, geometry, and environmental storytelling.',
      sourceFolder: '09_Architecture_And_Place',
      isPrimary: false
    },
    {
      id: 'machines-motion',
      title: 'Machines And Motion',
      slug: 'photography-machines-motion',
      heroText: 'Mechanical detail, automotive energy, and object-focused motion imagery.',
      webDescription: 'This gallery is centered on motorcycles, vehicles, and machine surfaces. Some images emphasize precision and texture, while others lean into speed, stance, and attitude. Together they present a sharper, more industrial side of the portfolio that can connect with automotive, sport, and product-driven clients.',
      metaDescription: 'Motorcycle and machine photography focused on detail, movement, texture, and visual attitude.',
      sourceFolder: '07_Machines_And_Motion',
      isPrimary: false
    },
    {
      id: 'experimental-objects',
      title: 'Experimental Object Studies',
      slug: 'photography-experimental-objects',
      heroText: 'Symbolic object work shaped by abstraction, play, and visual experimentation.',
      webDescription: 'These images treat everyday objects as material for concept, mood, and visual play. Rather than functioning as classic still life, they push toward symbolism, abstraction, and image-based ideas. This section is useful for showing creative range and for demonstrating a more exploratory way of thinking through photography.',
      metaDescription: 'Experimental object photography exploring abstraction, symbolism, and concept-driven image making.',
      sourceFolder: '08_Experimental_Object_Studies',
      isPrimary: false
    },
    {
      id: 'nature-animals',
      title: 'Nature And Animal Details',
      slug: 'photography-nature-animals',
      heroText: 'Organic studies of plants, animals, color, and texture.',
      webDescription: 'This gallery gathers smaller observations from the natural world, from flowers and foliage to animal portraits and surface detail. The images add softness, contrast, and breathing space to the broader portfolio while still keeping a clear visual style. They work well as supporting material in a portfolio that wants variation without losing coherence.',
      metaDescription: 'Nature detail photography featuring plants, animals, color, texture, and quiet visual studies.',
      sourceFolder: '10_Nature_And_Animal_Details',
      isPrimary: false
    }
  ],
  getCategory(id) {
    return this.categories.find(c => c.id === id);
  },
  getPrimary() {
    return this.categories.filter(c => c.isPrimary);
  },
  getSecondary() {
    return this.categories.filter(c => !c.isPrimary);
  },
  getPrev(id) {
    const i = this.categories.findIndex(c => c.id === id);
    return this.categories[(i - 1 + this.categories.length) % this.categories.length];
  },
  getNext(id) {
    const i = this.categories.findIndex(c => c.id === id);
    return this.categories[(i + 1) % this.categories.length];
  }
};
// Generated image data — populated from AI classification archive

const selectedWorkImages = [
  { file: '01__001__Albums__Boring___DSCF8862.jpg', label: '001 Albums Boring' },
  { file: '02__015__Albums__Mrigh__DSCF7361.jpg', label: '015 Albums Mrigh' },
  { file: '03__018__Albums__Mrigh__kef-under-water.jpg', label: '018 Albums Mrigh kef-under-water' },
  { file: '04__027__Albums__Reading_Writing___Part_1__DSCF2500.jpg', label: '027 Albums Reading Writing Part 1' },
  { file: '05__032__Albums__Reading_Writing___Part_2__DSCF1063.jpg', label: '032 Albums Reading Writing Part 2' },
  { file: '06__053__Albums__Reading_Writing___Part_3__IMG_20210330_105736_1.jpg', label: '053 Albums Reading Writing Part 3 IMG 20210330 105736 1' },
  { file: '07__064__Albums__Time_Eats_Everything___DSCF0076.jpg', label: '064 Albums Time Eats Everything' },
  { file: '08__072__Albums__Time_Eats_Everything___DSCF0109s.jpg', label: '072 Albums Time Eats Everything s' },
  { file: '09__079__Commercial_photography___DSCF0358.jpg', label: '079 Commercial photography' },
  { file: '10__082__Commercial_photography___DSCF4469.jpg', label: '082 Commercial photography' },
  { file: '11__092__Creativity_on_Portrait_pictures_needs_rapport___DSCF0201.jpg', label: '092 Creativity on Portrait pictures needs rapport' },
  { file: '12__100__Creativity_on_Portrait_pictures_needs_rapport___DSCF06781.jpg', label: '100 Creativity on Portrait pictures needs rapport' },
  { file: '13__102__Creativity_on_Portrait_pictures_needs_rapport___DSCF42031-OS.jpg', label: '102 Creativity on Portrait pictures needs rapport -OS' },
  { file: '14__111__Person__Portrait__Camera-Raw.jpg', label: '111 Person Portrait Camera-Raw' },
  { file: '15__125__Person__Portrait__DSCF4186-OS.jpg', label: '125 Person Portrait -OS' },
  { file: '16__149__Posters__DSCF0300.jpg', label: '149 Posters' },
  { file: '17__150__Posters__DSCF2403.jpg', label: '150 Posters' },
  { file: '18__173__creativity___Bike_Pictures__DSCF0558.jpg', label: '173 creativity Bike Pictures' },
  { file: '19__198__creativity___Indoor_pictures__DSCF0224.jpg', label: '198 creativity Indoor pictures' },
  { file: '20__205__creativity___Indoor_pictures__DSCF0269.jpg', label: '205 creativity Indoor pictures' },
  { file: '21__218__creativity___Indoor_pictures__DSCF0370.jpg', label: '218 creativity Indoor pictures' },
  { file: '22__227__creativity___Indoor_pictures__DSCF0844-_2_.jpg', label: '227 creativity Indoor pictures - 2' },
  { file: '23__268__creativity___Outdoor_creativity___DSCF0948.jpg', label: '268 creativity Outdoor creativity' },
  { file: '24__281__creativity___Outdoor_creativity___DSCF4674.jpg', label: '281 creativity Outdoor creativity' },
];

const portrait_narratives_images = [
  { file: '027__Albums__Reading_Writing___Part_1__DSCF2500.jpg', label: 'Albums Reading Writing Part 1' },
  { file: '032__Albums__Reading_Writing___Part_2__DSCF1063.jpg', label: 'Albums Reading Writing Part 2' },
  { file: '111__Person__Portrait__Camera-Raw.jpg', label: 'Person Portrait Camera-Raw' },
  { file: '125__Person__Portrait__DSCF4186-OS.jpg', label: 'Person Portrait -OS' },
  { file: '020__Albums__Reading_Writing___Part_1__DSCF2472.jpg', label: 'Albums Reading Writing Part 1' },
  { file: '021__Albums__Reading_Writing___Part_1__DSCF2483.jpg', label: 'Albums Reading Writing Part 1' },
  { file: '022__Albums__Reading_Writing___Part_1__DSCF2485.jpg', label: 'Albums Reading Writing Part 1' },
  { file: '023__Albums__Reading_Writing___Part_1__DSCF2488.jpg', label: 'Albums Reading Writing Part 1' },
  { file: '024__Albums__Reading_Writing___Part_1__DSCF2489.jpg', label: 'Albums Reading Writing Part 1' },
  { file: '025__Albums__Reading_Writing___Part_1__DSCF2494.jpg', label: 'Albums Reading Writing Part 1' },
  { file: '026__Albums__Reading_Writing___Part_1__DSCF2495.jpg', label: 'Albums Reading Writing Part 1' },
  { file: '028__Albums__Reading_Writing___Part_1__DSCF2502.jpg', label: 'Albums Reading Writing Part 1' },
  { file: '029__Albums__Reading_Writing___Part_1__DSCF2504.jpg', label: 'Albums Reading Writing Part 1' },
  { file: '030__Albums__Reading_Writing___Part_2__DSCF1060.jpg', label: 'Albums Reading Writing Part 2' },
  { file: '031__Albums__Reading_Writing___Part_2__DSCF1063-_2_.jpg', label: 'Albums Reading Writing Part 2 - 2' },
  { file: '033__Albums__Reading_Writing___Part_2__DSCF1064.jpg', label: 'Albums Reading Writing Part 2' },
  { file: '034__Albums__Reading_Writing___Part_2__DSCF1065.jpg', label: 'Albums Reading Writing Part 2' },
  { file: '035__Albums__Reading_Writing___Part_2__DSCF1076.jpg', label: 'Albums Reading Writing Part 2' },
  { file: '036__Albums__Reading_Writing___Part_2__DSCF1078.jpg', label: 'Albums Reading Writing Part 2' },
  { file: '037__Albums__Reading_Writing___Part_2__DSCF1082.jpg', label: 'Albums Reading Writing Part 2' },
  { file: '038__Albums__Reading_Writing___Part_2__DSCF1130.jpg', label: 'Albums Reading Writing Part 2' },
  { file: '039__Albums__Reading_Writing___Part_2__r_w-cover.jpg', label: 'Albums Reading Writing Part 2 r w-cover' },
  { file: '040__Albums__Reading_Writing___Part_2__r_w-cover1.jpg', label: 'Albums Reading Writing Part 2 r w-cover1' },
  { file: '101__Creativity_on_Portrait_pictures_needs_rapport___DSCF15721.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '104__Creativity_on_Portrait_pictures_needs_rapport___DSCF5637.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '105__Creativity_on_Portrait_pictures_needs_rapport___DSCF5645.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '106__Creativity_on_Portrait_pictures_needs_rapport___DSCF6331.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '109__Creativity_on_Portrait_pictures_needs_rapport___mid-marwen1.jpg', label: 'Creativity on Portrait pictures needs rapport mid-marwen1' },
  { file: '110__Person__Portrait__B_W.jpg', label: 'Person Portrait B W' },
  { file: '112__Person__Portrait__DSCF00101.jpg', label: 'Person Portrait' },
  { file: '117__Person__Portrait__DSCF0263.jpg', label: 'Person Portrait' },
  { file: '118__Person__Portrait__DSCF0268.jpg', label: 'Person Portrait' },
  { file: '119__Person__Portrait__DSCF0357.jpg', label: 'Person Portrait' },
  { file: '120__Person__Portrait__DSCF0378.jpg', label: 'Person Portrait' },
  { file: '121__Person__Portrait__DSCF03782.jpg', label: 'Person Portrait' },
  { file: '122__Person__Portrait__DSCF0478.jpg', label: 'Person Portrait' },
  { file: '123__Person__Portrait__DSCF0565.jpg', label: 'Person Portrait' },
  { file: '126__Person__Portrait__DSCF4203-OS.jpg', label: 'Person Portrait -OS' },
  { file: '127__Person__Portrait__DSCF4680.jpg', label: 'Person Portrait' },
  { file: '129__Person__Portrait__DSCF6345.jpg', label: 'Person Portrait' },
  { file: '130__Person__Portrait__DSCF6346.jpg', label: 'Person Portrait' },
  { file: '131__Person__Portrait__DSCF6399.jpg', label: 'Person Portrait' },
  { file: '132__Person__Portrait__DSCF6406.jpg', label: 'Person Portrait' },
  { file: '133__Person__Portrait__DSCF6413.jpg', label: 'Person Portrait' },
  { file: '134__Person__Portrait__DSCF6414.jpg', label: 'Person Portrait' },
  { file: '135__Person__Portrait__DSCF6415.jpg', label: 'Person Portrait' },
  { file: '136__Person__Portrait__DSCF6424.jpg', label: 'Person Portrait' },
  { file: '139__Person__Portrait__DSCF9873.jpg', label: 'Person Portrait' },
  { file: '140__Person__Portrait__DSCF9932.jpg', label: 'Person Portrait' },
  { file: '141__Person__Portrait__DSCF9937.jpg', label: 'Person Portrait' },
  { file: '142__Person__Portrait__DSCF9947.jpg', label: 'Person Portrait' },
  { file: '144__Person__Portrait__mirou.jpg', label: 'Person Portrait mirou' },
  { file: '145__Person__Portrait__old-mirou-mirou.jpg', label: 'Person Portrait old-mirou-mirou' },
];

const posters_key_art_images = [
  { file: '149__Posters__DSCF0300.jpg', label: 'Posters' },
  { file: '150__Posters__DSCF2403.jpg', label: 'Posters' },
  { file: '014__Albums__Mrigh__DSCF7336.jpg', label: 'Albums Mrigh' },
  { file: '017__Albums__Mrigh__DSCF73ds36.jpg', label: 'Albums Mrigh DSCF73ds36' },
  { file: '019__Albums__Mrigh__mrogh.jpg', label: 'Albums Mrigh mrogh' },
  { file: '093__Creativity_on_Portrait_pictures_needs_rapport___DSCF0449.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '146__Posters__DSCF0064fsdqjlm.jpg', label: 'Posters fsdqjlm' },
  { file: '147__Posters__DSCF0064fsdqjlm1.jpg', label: 'Posters fsdqjlm1' },
  { file: '148__Posters__DSCF0194.jpg', label: 'Posters' },
  { file: '151__Posters__DSCF6820.jpg', label: 'Posters' },
  { file: '152__Posters__DSCF9295-B_W-Edition.jpg', label: 'Posters -B W-Edition' },
  { file: '153__Posters__DSCF9295.jpg', label: 'Posters' },
  { file: '154__Posters__DSCF9387.jpg', label: 'Posters' },
  { file: '155__Posters__DSCF93872.jpg', label: 'Posters' },
  { file: '156__Posters__DSCF93873.jpg', label: 'Posters' },
  { file: '157__Posters__Untitled-1-Recovered1.jpg', label: 'Posters Untitled-1-Recovered1' },
  { file: '158__Posters__alien1.jpg', label: 'Posters alien1' },
  { file: '159__Posters__final-cover.jpg', label: 'Posters final-cover' },
  { file: '160__Posters__map.jpg', label: 'Posters map' },
  { file: '161__Posters__map1.jpg', label: 'Posters map1' },
  { file: '162__Posters__mid-marwen.jpg', label: 'Posters mid-marwen' },
  { file: '163__Posters__mid-marwen2.jpg', label: 'Posters mid-marwen2' },
  { file: '164__Posters__stilization-2.jpg', label: 'Posters stilization-2' },
];

const product_commercial_images = [
  { file: '079__Commercial_photography___DSCF0358.jpg', label: 'Commercial photography' },
  { file: '082__Commercial_photography___DSCF4469.jpg', label: 'Commercial photography' },
  { file: '080__Commercial_photography___DSCF0361.jpg', label: 'Commercial photography' },
  { file: '081__Commercial_photography___DSCF0383.jpg', label: 'Commercial photography' },
  { file: '083__Commercial_photography___DSCF4470.jpg', label: 'Commercial photography' },
  { file: '084__Commercial_photography___DSCF4471.jpg', label: 'Commercial photography' },
  { file: '085__Commercial_photography___DSCF4473.jpg', label: 'Commercial photography' },
  { file: '086__Commercial_photography___DSCF4475.jpg', label: 'Commercial photography' },
  { file: '087__Commercial_photography___DSCF4479.jpg', label: 'Commercial photography' },
  { file: '088__Commercial_photography___DSCF4481.jpg', label: 'Commercial photography' },
  { file: '089__Commercial_photography___DSCF4484.jpg', label: 'Commercial photography' },
];

const editorial_still_life_images = [
  { file: '053__Albums__Reading_Writing___Part_3__IMG_20210330_105736_1.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105736 1' },
  { file: '041__Albums__Reading_Writing___Part_3__IMG_20210330_104816.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 104816' },
  { file: '042__Albums__Reading_Writing___Part_3__IMG_20210330_104942.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 104942' },
  { file: '043__Albums__Reading_Writing___Part_3__IMG_20210330_105001.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105001' },
  { file: '044__Albums__Reading_Writing___Part_3__IMG_20210330_105005.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105005' },
  { file: '045__Albums__Reading_Writing___Part_3__IMG_20210330_105013.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105013' },
  { file: '046__Albums__Reading_Writing___Part_3__IMG_20210330_105058.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105058' },
  { file: '047__Albums__Reading_Writing___Part_3__IMG_20210330_105139.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105139' },
  { file: '048__Albums__Reading_Writing___Part_3__IMG_20210330_105142.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105142' },
  { file: '049__Albums__Reading_Writing___Part_3__IMG_20210330_105429_1.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105429 1' },
  { file: '050__Albums__Reading_Writing___Part_3__IMG_20210330_105627_1.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105627 1' },
  { file: '051__Albums__Reading_Writing___Part_3__IMG_20210330_105650_1.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105650 1' },
  { file: '052__Albums__Reading_Writing___Part_3__IMG_20210330_105712.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105712' },
  { file: '054__Albums__Reading_Writing___Part_3__IMG_20210330_105800.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105800' },
  { file: '055__Albums__Reading_Writing___Part_3__IMG_20210330_105845.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105845' },
  { file: '056__Albums__Reading_Writing___Part_3__IMG_20210330_105859.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105859' },
  { file: '057__Albums__Reading_Writing___Part_3__IMG_20210330_105910.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 105910' },
  { file: '058__Albums__Reading_Writing___Part_3__IMG_20210330_110025.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 110025' },
  { file: '059__Albums__Reading_Writing___Part_3__IMG_20210330_110243.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 110243' },
  { file: '060__Albums__Reading_Writing___Part_3__IMG_20210330_110342_1.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 110342 1' },
  { file: '061__Albums__Reading_Writing___Part_3__IMG_20210330_110432_1.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 110432 1' },
  { file: '062__Albums__Reading_Writing___Part_3__IMG_20210330_110501_1.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 110501 1' },
  { file: '063__Albums__Reading_Writing___Part_3__IMG_20210330_110533.jpg', label: 'Albums Reading Writing Part 3 IMG 20210330 110533' },
  { file: '099__Creativity_on_Portrait_pictures_needs_rapport___DSCF0639.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '189__creativity___Indoor_pictures__1639055008860.jpg', label: 'creativity Indoor pictures 1639055008860' },
  { file: '190__creativity___Indoor_pictures__1639055008872.jpg', label: 'creativity Indoor pictures 1639055008872' },
  { file: '191__creativity___Indoor_pictures__1639055008884.jpg', label: 'creativity Indoor pictures 1639055008884' },
  { file: '192__creativity___Indoor_pictures__1639055008897.jpg', label: 'creativity Indoor pictures 1639055008897' },
  { file: '193__creativity___Indoor_pictures__1639055008908.jpg', label: 'creativity Indoor pictures 1639055008908' },
  { file: '194__creativity___Indoor_pictures__1639055008922.jpg', label: 'creativity Indoor pictures 1639055008922' },
  { file: '195__creativity___Indoor_pictures__1639055008934.jpg', label: 'creativity Indoor pictures 1639055008934' },
  { file: '196__creativity___Indoor_pictures__DSCF0164.jpg', label: 'creativity Indoor pictures' },
  { file: '197__creativity___Indoor_pictures__DSCF0169.jpg', label: 'creativity Indoor pictures' },
  { file: '211__creativity___Indoor_pictures__DSCF0291.jpg', label: 'creativity Indoor pictures' },
  { file: '233__creativity___Indoor_pictures__Snapchat-491666996.jpg', label: 'creativity Indoor pictures Snapchat-491666996' },
  { file: '234__creativity___Indoor_pictures__Snapchat-847534232.jpg', label: 'creativity Indoor pictures Snapchat-847534232' },
];

const conceptual_portraits_images = [
  { file: '001__Albums__Boring___DSCF8862.jpg', label: 'Albums Boring' },
  { file: '092__Creativity_on_Portrait_pictures_needs_rapport___DSCF0201.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '100__Creativity_on_Portrait_pictures_needs_rapport___DSCF06781.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '102__Creativity_on_Portrait_pictures_needs_rapport___DSCF42031-OS.jpg', label: 'Creativity on Portrait pictures needs rapport -OS' },
  { file: '227__creativity___Indoor_pictures__DSCF0844-_2_.jpg', label: 'creativity Indoor pictures - 2' },
  { file: '002__Albums__Boring___DSCF8869.jpg', label: 'Albums Boring' },
  { file: '003__Albums__Boring___DSCF8872.jpg', label: 'Albums Boring' },
  { file: '004__Albums__Boring___DSCF9738.jpg', label: 'Albums Boring' },
  { file: '005__Albums__Boring___DSCF9744.jpg', label: 'Albums Boring' },
  { file: '006__Albums__Boring___DSCF9760.jpg', label: 'Albums Boring' },
  { file: '007__Albums__Boring___DSCF9767.jpg', label: 'Albums Boring' },
  { file: '008__Albums__Boring___DSCF9768.jpg', label: 'Albums Boring' },
  { file: '009__Albums__Boring___DSCF9770.jpg', label: 'Albums Boring' },
  { file: '010__Albums__Boring___DSCF9790.jpg', label: 'Albums Boring' },
  { file: '011__Albums__Boring___DSCF9791.jpg', label: 'Albums Boring' },
  { file: '012__Albums__Boring___DSCF9794.jpg', label: 'Albums Boring' },
  { file: '013__Albums__Boring___DSCF9797.jpg', label: 'Albums Boring' },
  { file: '094__Creativity_on_Portrait_pictures_needs_rapport___DSCF0516.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '095__Creativity_on_Portrait_pictures_needs_rapport___DSCF05161.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '096__Creativity_on_Portrait_pictures_needs_rapport___DSCF0557.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '097__Creativity_on_Portrait_pictures_needs_rapport___DSCF05682.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '098__Creativity_on_Portrait_pictures_needs_rapport___DSCF06051.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '103__Creativity_on_Portrait_pictures_needs_rapport___DSCF5441-Recovered.jpg', label: 'Creativity on Portrait pictures needs rapport -Recovered' },
  { file: '107__Creativity_on_Portrait_pictures_needs_rapport___DSCF6456.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '108__Creativity_on_Portrait_pictures_needs_rapport___DSCF6544-Recovered.jpg', label: 'Creativity on Portrait pictures needs rapport -Recovered' },
  { file: '113__Person__Portrait__DSCF0087hjklg.jpg', label: 'Person Portrait hjklg' },
  { file: '114__Person__Portrait__DSCF0109.jpg', label: 'Person Portrait' },
  { file: '115__Person__Portrait__DSCF0110.jpg', label: 'Person Portrait' },
  { file: '116__Person__Portrait__DSCF0142.jpg', label: 'Person Portrait' },
  { file: '124__Person__Portrait__DSCF0841.jpg', label: 'Person Portrait' },
  { file: '128__Person__Portrait__DSCF5117-Recovered1.jpg', label: 'Person Portrait -Recovered1' },
  { file: '137__Person__Portrait__DSCF6447.jpg', label: 'Person Portrait' },
  { file: '138__Person__Portrait__DSCF68201.jpg', label: 'Person Portrait' },
  { file: '143__Person__Portrait__alien.jpg', label: 'Person Portrait alien' },
  { file: '228__creativity___Indoor_pictures__DSCF0844.jpg', label: 'creativity Indoor pictures' },
  { file: '229__creativity___Indoor_pictures__DSCF08441.jpg', label: 'creativity Indoor pictures' },
  { file: '230__creativity___Indoor_pictures__DSCF08442.jpg', label: 'creativity Indoor pictures' },
  { file: '231__creativity___Indoor_pictures__DSCF08443.jpg', label: 'creativity Indoor pictures' },
  { file: '232__creativity___Indoor_pictures__DSCF08444.jpg', label: 'creativity Indoor pictures' },
];

const night_neon_images = [
  { file: '064__Albums__Time_Eats_Everything___DSCF0076.jpg', label: 'Albums Time Eats Everything' },
  { file: '072__Albums__Time_Eats_Everything___DSCF0109s.jpg', label: 'Albums Time Eats Everything s' },
  { file: '065__Albums__Time_Eats_Everything___DSCF0085.jpg', label: 'Albums Time Eats Everything' },
  { file: '066__Albums__Time_Eats_Everything___DSCF0095-Recovered.jpg', label: 'Albums Time Eats Everything -Recovered' },
  { file: '067__Albums__Time_Eats_Everything___DSCF0096.jpg', label: 'Albums Time Eats Everything' },
  { file: '068__Albums__Time_Eats_Everything___DSCF00961.jpg', label: 'Albums Time Eats Everything' },
  { file: '069__Albums__Time_Eats_Everything___DSCF0101.jpg', label: 'Albums Time Eats Everything' },
  { file: '070__Albums__Time_Eats_Everything___DSCF01011.jpg', label: 'Albums Time Eats Everything' },
  { file: '071__Albums__Time_Eats_Everything___DSCF0102.jpg', label: 'Albums Time Eats Everything' },
  { file: '073__Albums__Time_Eats_Everything___DSCF0113.jpg', label: 'Albums Time Eats Everything' },
  { file: '074__Albums__Time_Eats_Everything___DSCF0114.jpg', label: 'Albums Time Eats Everything' },
  { file: '075__Albums__Time_Eats_Everything___DSCF0117.jpg', label: 'Albums Time Eats Everything' },
  { file: '076__Albums__Time_Eats_Everything___DSCF0119.jpg', label: 'Albums Time Eats Everything' },
  { file: '077__Albums__Time_Eats_Everything___DSCF0121.jpg', label: 'Albums Time Eats Everything' },
  { file: '078__Albums__Time_Eats_Everything___DSCF0125.jpg', label: 'Albums Time Eats Everything' },
  { file: '090__Creativity_on_Portrait_pictures_needs_rapport___DSCF0084.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '091__Creativity_on_Portrait_pictures_needs_rapport___DSCF0087.jpg', label: 'Creativity on Portrait pictures needs rapport' },
  { file: '235__creativity___Outdoor_creativity___DSCF0112jkdflsmq.jpg', label: 'creativity Outdoor creativity jkdflsmq' },
  { file: '236__creativity___Outdoor_creativity___DSCF0115j.jpg', label: 'creativity Outdoor creativity j' },
  { file: '237__creativity___Outdoor_creativity___DSCF0151.jpg', label: 'creativity Outdoor creativity' },
  { file: '238__creativity___Outdoor_creativity___DSCF01511.jpg', label: 'creativity Outdoor creativity' },
  { file: '239__creativity___Outdoor_creativity___DSCF0153.jpg', label: 'creativity Outdoor creativity' },
];

const architecture_place_images = [
  { file: '015__Albums__Mrigh__DSCF7361.jpg', label: 'Albums Mrigh' },
  { file: '018__Albums__Mrigh__kef-under-water.jpg', label: 'Albums Mrigh kef-under-water' },
  { file: '268__creativity___Outdoor_creativity___DSCF0948.jpg', label: 'creativity Outdoor creativity' },
  { file: '281__creativity___Outdoor_creativity___DSCF4674.jpg', label: 'creativity Outdoor creativity' },
  { file: '016__Albums__Mrigh__DSCF7367.jpg', label: 'Albums Mrigh' },
  { file: '217__creativity___Indoor_pictures__DSCF0338.jpg', label: 'creativity Indoor pictures' },
  { file: '224__creativity___Indoor_pictures__DSCF0783.jpg', label: 'creativity Indoor pictures' },
  { file: '225__creativity___Indoor_pictures__DSCF0789.jpg', label: 'creativity Indoor pictures' },
  { file: '226__creativity___Indoor_pictures__DSCF0824.jpg', label: 'creativity Indoor pictures' },
  { file: '259__creativity___Outdoor_creativity___DSCF0741.jpg', label: 'creativity Outdoor creativity' },
  { file: '260__creativity___Outdoor_creativity___DSCF0742.jpg', label: 'creativity Outdoor creativity' },
  { file: '261__creativity___Outdoor_creativity___DSCF0743.jpg', label: 'creativity Outdoor creativity' },
  { file: '262__creativity___Outdoor_creativity___DSCF0744.jpg', label: 'creativity Outdoor creativity' },
  { file: '263__creativity___Outdoor_creativity___DSCF0745.jpg', label: 'creativity Outdoor creativity' },
  { file: '264__creativity___Outdoor_creativity___DSCF0751.jpg', label: 'creativity Outdoor creativity' },
  { file: '265__creativity___Outdoor_creativity___DSCF0752.jpg', label: 'creativity Outdoor creativity' },
  { file: '266__creativity___Outdoor_creativity___DSCF0756.jpg', label: 'creativity Outdoor creativity' },
  { file: '267__creativity___Outdoor_creativity___DSCF0790.jpg', label: 'creativity Outdoor creativity' },
  { file: '269__creativity___Outdoor_creativity___DSCF0949.jpg', label: 'creativity Outdoor creativity' },
  { file: '270__creativity___Outdoor_creativity___DSCF0952.jpg', label: 'creativity Outdoor creativity' },
  { file: '271__creativity___Outdoor_creativity___DSCF0953.jpg', label: 'creativity Outdoor creativity' },
  { file: '272__creativity___Outdoor_creativity___DSCF0954.jpg', label: 'creativity Outdoor creativity' },
  { file: '273__creativity___Outdoor_creativity___DSCF4505.jpg', label: 'creativity Outdoor creativity' },
  { file: '274__creativity___Outdoor_creativity___DSCF4521.jpg', label: 'creativity Outdoor creativity' },
  { file: '275__creativity___Outdoor_creativity___DSCF4522.jpg', label: 'creativity Outdoor creativity' },
  { file: '277__creativity___Outdoor_creativity___DSCF4538.jpg', label: 'creativity Outdoor creativity' },
  { file: '278__creativity___Outdoor_creativity___DSCF4571.jpg', label: 'creativity Outdoor creativity' },
  { file: '279__creativity___Outdoor_creativity___DSCF4595.jpg', label: 'creativity Outdoor creativity' },
  { file: '280__creativity___Outdoor_creativity___DSCF4648.jpg', label: 'creativity Outdoor creativity' },
  { file: '282__creativity___Outdoor_creativity___DSCF4688.jpg', label: 'creativity Outdoor creativity' },
  { file: '283__creativity___Outdoor_creativity___DSCF4699.jpg', label: 'creativity Outdoor creativity' },
  { file: '284__creativity___Outdoor_creativity___DSCF4707.jpg', label: 'creativity Outdoor creativity' },
];

const machines_motion_images = [
  { file: '173__creativity___Bike_Pictures__DSCF0558.jpg', label: 'creativity Bike Pictures' },
  { file: '165__creativity___Bike_Pictures__DSCF0422.jpg', label: 'creativity Bike Pictures' },
  { file: '166__creativity___Bike_Pictures__DSCF0423.jpg', label: 'creativity Bike Pictures' },
  { file: '167__creativity___Bike_Pictures__DSCF0428.jpg', label: 'creativity Bike Pictures' },
  { file: '168__creativity___Bike_Pictures__DSCF0456.jpg', label: 'creativity Bike Pictures' },
  { file: '169__creativity___Bike_Pictures__DSCF0537.jpg', label: 'creativity Bike Pictures' },
  { file: '170__creativity___Bike_Pictures__DSCF0538.jpg', label: 'creativity Bike Pictures' },
  { file: '171__creativity___Bike_Pictures__DSCF0549.jpg', label: 'creativity Bike Pictures' },
  { file: '172__creativity___Bike_Pictures__DSCF0551.jpg', label: 'creativity Bike Pictures' },
  { file: '174__creativity___Bike_Pictures__DSCF0559.jpg', label: 'creativity Bike Pictures' },
  { file: '175__creativity___Bike_Pictures__DSCF0560.jpg', label: 'creativity Bike Pictures' },
  { file: '176__creativity___Bike_Pictures__DSCF0563.jpg', label: 'creativity Bike Pictures' },
  { file: '177__creativity___Bike_Pictures__DSCF0564.jpg', label: 'creativity Bike Pictures' },
  { file: '178__creativity___Bike_Pictures__DSCF0569.jpg', label: 'creativity Bike Pictures' },
  { file: '179__creativity___Bike_Pictures__DSCF0572.jpg', label: 'creativity Bike Pictures' },
  { file: '180__creativity___Bike_Pictures__DSCF0579.jpg', label: 'creativity Bike Pictures' },
  { file: '181__creativity___Bike_Pictures__DSCF0581.jpg', label: 'creativity Bike Pictures' },
  { file: '182__creativity___Bike_Pictures__DSCF0583.jpg', label: 'creativity Bike Pictures' },
  { file: '183__creativity___Bike_Pictures__DSCF05834.jpg', label: 'creativity Bike Pictures' },
  { file: '184__creativity___Bike_Pictures__DSCF0589.jpg', label: 'creativity Bike Pictures' },
  { file: '185__creativity___Bike_Pictures__DSCF0590.jpg', label: 'creativity Bike Pictures' },
  { file: '186__creativity___Bike_Pictures__DSCF0592.jpg', label: 'creativity Bike Pictures' },
  { file: '187__creativity___Bike_Pictures__DSCF0594.jpg', label: 'creativity Bike Pictures' },
  { file: '188__creativity___Bike_Pictures__DSCF0638.jpg', label: 'creativity Bike Pictures' },
  { file: '208__creativity___Indoor_pictures__DSCF0275.jpg', label: 'creativity Indoor pictures' },
  { file: '209__creativity___Indoor_pictures__DSCF0280.jpg', label: 'creativity Indoor pictures' },
  { file: '210__creativity___Indoor_pictures__DSCF0290.jpg', label: 'creativity Indoor pictures' },
];

const experimental_objects_images = [
  { file: '198__creativity___Indoor_pictures__DSCF0224.jpg', label: 'creativity Indoor pictures' },
  { file: '205__creativity___Indoor_pictures__DSCF0269.jpg', label: 'creativity Indoor pictures' },
  { file: '218__creativity___Indoor_pictures__DSCF0370.jpg', label: 'creativity Indoor pictures' },
  { file: '199__creativity___Indoor_pictures__DSCF0224_1.jpg', label: 'creativity Indoor pictures 1' },
  { file: '200__creativity___Indoor_pictures__DSCF0225_1_.jpg', label: 'creativity Indoor pictures 1' },
  { file: '201__creativity___Indoor_pictures__DSCF0225_1__1.jpg', label: 'creativity Indoor pictures 1 1' },
  { file: '202__creativity___Indoor_pictures__DSCF0226.jpg', label: 'creativity Indoor pictures' },
  { file: '203__creativity___Indoor_pictures__DSCF02261.jpg', label: 'creativity Indoor pictures' },
  { file: '204__creativity___Indoor_pictures__DSCF0226_1.jpg', label: 'creativity Indoor pictures 1' },
  { file: '206__creativity___Indoor_pictures__DSCF0270.jpg', label: 'creativity Indoor pictures' },
  { file: '207__creativity___Indoor_pictures__DSCF0271.jpg', label: 'creativity Indoor pictures' },
  { file: '212__creativity___Indoor_pictures__DSCF0306.jpg', label: 'creativity Indoor pictures' },
  { file: '213__creativity___Indoor_pictures__DSCF0312.jpg', label: 'creativity Indoor pictures' },
  { file: '214__creativity___Indoor_pictures__DSCF0320.jpg', label: 'creativity Indoor pictures' },
  { file: '215__creativity___Indoor_pictures__DSCF0322.jpg', label: 'creativity Indoor pictures' },
  { file: '216__creativity___Indoor_pictures__DSCF0335.jpg', label: 'creativity Indoor pictures' },
  { file: '219__creativity___Indoor_pictures__DSCF0371.jpg', label: 'creativity Indoor pictures' },
  { file: '220__creativity___Indoor_pictures__DSCF0373.jpg', label: 'creativity Indoor pictures' },
  { file: '221__creativity___Indoor_pictures__DSCF0379.jpg', label: 'creativity Indoor pictures' },
  { file: '222__creativity___Indoor_pictures__DSCF0380.jpg', label: 'creativity Indoor pictures' },
  { file: '223__creativity___Indoor_pictures__DSCF0386.jpg', label: 'creativity Indoor pictures' },
  { file: '240__creativity___Outdoor_creativity___DSCF0480-2.jpg', label: 'creativity Outdoor creativity -2' },
  { file: '241__creativity___Outdoor_creativity___DSCF0481-2.jpg', label: 'creativity Outdoor creativity -2' },
  { file: '242__creativity___Outdoor_creativity___DSCF0518.jpg', label: 'creativity Outdoor creativity' },
  { file: '243__creativity___Outdoor_creativity___DSCF0519.jpg', label: 'creativity Outdoor creativity' },
  { file: '244__creativity___Outdoor_creativity___DSCF0650.jpg', label: 'creativity Outdoor creativity' },
  { file: '245__creativity___Outdoor_creativity___DSCF0651.jpg', label: 'creativity Outdoor creativity' },
  { file: '246__creativity___Outdoor_creativity___DSCF0652.jpg', label: 'creativity Outdoor creativity' },
  { file: '247__creativity___Outdoor_creativity___DSCF0663.jpg', label: 'creativity Outdoor creativity' },
  { file: '248__creativity___Outdoor_creativity___DSCF0665.jpg', label: 'creativity Outdoor creativity' },
  { file: '250__creativity___Outdoor_creativity___DSCF0691.jpg', label: 'creativity Outdoor creativity' },
];

const nature_animals_images = [
  { file: '249__creativity___Outdoor_creativity___DSCF0670.jpg', label: 'creativity Outdoor creativity' },
  { file: '251__creativity___Outdoor_creativity___DSCF0711.jpg', label: 'creativity Outdoor creativity' },
  { file: '252__creativity___Outdoor_creativity___DSCF0712.jpg', label: 'creativity Outdoor creativity' },
  { file: '253__creativity___Outdoor_creativity___DSCF0714.jpg', label: 'creativity Outdoor creativity' },
  { file: '254__creativity___Outdoor_creativity___DSCF0735.jpg', label: 'creativity Outdoor creativity' },
  { file: '255__creativity___Outdoor_creativity___DSCF07351.jpg', label: 'creativity Outdoor creativity' },
  { file: '256__creativity___Outdoor_creativity___DSCF07352.jpg', label: 'creativity Outdoor creativity' },
  { file: '257__creativity___Outdoor_creativity___DSCF07353.jpg', label: 'creativity Outdoor creativity' },
  { file: '258__creativity___Outdoor_creativity___DSCF07354.jpg', label: 'creativity Outdoor creativity' },
  { file: '276__creativity___Outdoor_creativity___DSCF4532.jpg', label: 'creativity Outdoor creativity' },
];

const categoryCoverImages = {
  'portrait-narratives': '027__Albums__Reading_Writing___Part_1__DSCF2500.jpg',
  'posters-key-art': '149__Posters__DSCF0300.jpg',
  'product-commercial': '079__Commercial_photography___DSCF0358.jpg',
  'editorial-still-life': '053__Albums__Reading_Writing___Part_3__IMG_20210330_105736_1.jpg',
  'conceptual-portraits': '001__Albums__Boring___DSCF8862.jpg',
  'night-neon': '064__Albums__Time_Eats_Everything___DSCF0076.jpg',
  'architecture-place': '015__Albums__Mrigh__DSCF7361.jpg',
  'machines-motion': '173__creativity___Bike_Pictures__DSCF0558.jpg',
  'experimental-objects': '198__creativity___Indoor_pictures__DSCF0224.jpg',
  'nature-animals': '249__creativity___Outdoor_creativity___DSCF0670.jpg',
};

const categoryImages = {
  'portrait-narratives': portrait_narratives_images,
  'posters-key-art': posters_key_art_images,
  'product-commercial': product_commercial_images,
  'editorial-still-life': editorial_still_life_images,
  'conceptual-portraits': conceptual_portraits_images,
  'night-neon': night_neon_images,
  'architecture-place': architecture_place_images,
  'machines-motion': machines_motion_images,
  'experimental-objects': experimental_objects_images,
  'nature-animals': nature_animals_images,
};

const categoryImageFolders = {
  'portrait-narratives': 'portrait-narratives',
  'posters-key-art': 'posters-key-art',
  'product-commercial': 'product-commercial',
  'editorial-still-life': 'editorial-still-life',
  'conceptual-portraits': 'conceptual-portraits',
  'night-neon': 'night-neon',
  'architecture-place': 'architecture-place',
  'machines-motion': 'machines-motion',
  'experimental-objects': 'experimental-objects',
  'nature-animals': 'nature-animals',
};
